name: Cloud Run Deployment Workflow

on:
  workflow_call:
    inputs:
      PROJECT_ID:
        required: true
        type: string
      SERVICE:
        required: true
        type: string
      REGION:
        required: true
        type: string
        default: us-central1
      ENV:
        required: true
        type: string
      WORK_DIR:
        required: true
        type: string
    # secrets:
    #   SA_GITHUB_ACTIONS:
    #     required: true

jobs:
  deploy-cloud-run-service:
    name: Deploying ${{inputs.SERVICE}}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - id: 'auth'
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{ secrets.SA_GITHUB_ACTIONS }}'
          create_credentials_file: true
          export_environment_variables: true
      
      - name: Setup Cloud SDK
        uses: google-github-actions/setup-gcloud@v0

      - name: Authorize Docker push
        run: gcloud auth configure-docker

      - name: Fix env vars
        run: |
          echo "SHORT_SHA=`echo ${GITHUB_SHA} | cut -c1-8`" >> $GITHUB_ENV

      - name: Build Container
        run: |-
          docker build -t gcr.io/${{ inputs.PROJECT_ID }}/${{ inputs.SERVICE }}:${{ github.sha }} -f Dockerfile ../ --build-arg ENV=${{ inputs.ENV }} --build-arg GIT_VERSION=${SHORT_SHA}
          docker push gcr.io/${{ inputs.PROJECT_ID }}/${{ inputs.SERVICE }}:${{ github.sha }}
        working-directory: ${{inputs.WORK_DIR}}

      - name: Deploy to Cloud Run
        id: deploy
        uses: google-github-actions/deploy-cloudrun@v0
        with:
          service: ${{ inputs.SERVICE }}
          image: gcr.io/${{ inputs.PROJECT_ID }}/${{ inputs.SERVICE }}:${{ github.sha }}
          region: ${{ inputs.REGION }}
          flags: '--cpu=2 --memory=1Gi --concurrency=20 --allow-unauthenticated'
          env_vars: |
            SERVICE = ${{ inputs.SERVICE }}
            PROJECT_ID = ${{ inputs.PROJECT_ID }}
            GIT_VERSION = ${{ github.sha }}
      - name: Show Output
        run: echo ${{ steps.deploy.outputs.url }}