name: PubSub Push Subscription Workflow

on:
  workflow_call:
    inputs:
      ENDPOINT:
        required: true
        type: string
      SERVICE:
        required: true
        type: string
      ENV:
        required: true
        type: string
      TOPIC:
        required: true
        type: string
      PUB_SUB_PROJECT_ID:
        required: false
        type: string
        default: ${{ inputs.PROJECT_ID }}
      RETENTION:
        required: false
        type: string
        default: 7d
      ACK_DEADLINE:
        required: false
        type: number
        default: 120
      RETRY_POLICY:
        required: false
        type: boolean
      RETRY_MIN_DELAY:
        required: false
        type: string
        default: "10s"
      RETRY_MAX_DELAY:
        required: false
        type: string
        default: "600s"
    secrets:
      SA_CREDENTIALS:
        required: true
        description: The Service Account that will be used to perform changes on GCP
      PROJECT_ID:
        required: true
        description: The GCP project ID

jobs:
  deploy-cloud-run-service:
    runs-on: ubuntu-latest
    steps:
      - id: 'auth'
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{ secrets.SA_CREDENTIALS }}'
          create_credentials_file: true
          export_environment_variables: true

      - name: Setup Cloud SDK
        uses: google-github-actions/setup-gcloud@v0

      - name: Authorize Docker push
        run: gcloud auth configure-docker

      - name: Create/Update PubSub Subscription For ${{ inputs.ENDPOINT }}
        run: |-
          pushTopic=$(echo ${{ inputs.ENDPOINT }})
          subscriptionsKey=$(echo ${{ inputs.SERVICE }}-${{ inputs.ENV }}-${{ inputs.TOPIC }}-subscription)

          emptyResponse=$(echo "[]")
          output=$(gcloud pubsub subscriptions list --filter=name=projects/${{ secrets.PROJECT_ID }}/subscriptions/$subscriptionsKey --format="json")
          echo $output
          if [ "$output" == "$emptyResponse" ]; then
            echo "Creating new PubSub subscription"
            gcloud pubsub subscriptions create $subscriptionsKey \
              --topic=${{ inputs.TOPIC }} \
              --topic-project=${{ inputs.PUB_SUB_PROJECT_ID }} \
              --push-endpoint=$pushTopic \
              --message-retention-duration=${{ inputs.RETENTION }} \
              --ack-deadline=${{ inputs.ACK_DEADLINE }} \
              $(if ${{ inputs.RETRY_POLICY }}; then
                echo " --min-retry-delay=${{ inputs.RETRY_MIN_DELAY }} \
                       --max-retry-delay=${{ inputs.RETRY_MAX_DELAY }}";
                fi)
          else
            echo "Updating PubSub subscription"
            gcloud pubsub subscriptions update $subscriptionsKey \
              --push-endpoint=$pushTopic \
              --message-retention-duration=${{ inputs.RETENTION }} \
              --ack-deadline=${{ inputs.ACK_DEADLINE }} \
              $(if ${{ inputs.RETRY_POLICY }}; then
                echo " --min-retry-delay=${{ inputs.RETRY_MIN_DELAY }} \
                       --max-retry-delay=${{ inputs.RETRY_MAX_DELAY }}";
                fi)
          fi
